name: 'AIRBNB_PROJECT'
version: '1.0.0'


profile: 'AIRBNB_PROJECT'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"


models:
  AIRBNB_PROJECT:
   
    example:
      +materialized: view
